version: "3.9"

# Shared healthcheck defaults (interval, timeout, retries)
x-healthcheck-params: &healthcheckParams
  interval: ${HEALTHCHECK_INTERVAL:-5s}
  timeout: ${HEALTHCHECK_TIMEOUT:-3s}
  retries: ${HEALTHCHECK_RETRIES:-5}

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grimoire
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      <<: *healthcheckParams
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.12.1-slim
    image: grimoire-backend:latest
    ports:
      - "8000:8000"
    environment:
      APP_ENV: development
      PYTHONUNBUFFERED: "1"
      REDIS_URL: redis://redis:6379/0
      IMAGE_CACHE_TTL: 86400
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/grimoire
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      <<: *healthcheckParams
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  query:
    build:
      context: ./query
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.12.1-slim
    image: grimoire-query:latest
    ports:
      - "8080:8080"
    environment:
      # Pass through host OPENAI_API_KEY; ensure it's exported before compose up
      OPENAI_API_KEY: ${OPENAI_API_KEY:?set OPENAI_API_KEY environment variable}
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      <<: *healthcheckParams

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20-alpine
    image: grimoire-frontend:latest
    depends_on:
      backend:
        condition: service_healthy
      card-db:
        condition: service_healthy
      query:
        condition: service_healthy
    ports:
      - "3000:3000"
    # Hot reload development setup: bind mount source; keep node_modules inside container layer
    volumes:
      - ./webapp:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_BASE: http://backend:8000
      NEXT_PUBLIC_CARD_DB_BASE: http://card-db:8081
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      <<: *healthcheckParams

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: grimoireml-prometheus
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.retention.time=15d",
        "--web.enable-lifecycle",
      ]

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grimoireml-grafana
    depends_on:
      prometheus:
        condition: service_started
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_DEFAULT_THEME: light
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro

  redis:
    image: redis:7-alpine
    command:
      [
        "redis-server",
        "--save",
        "900",
        "1",
        "--maxmemory",
        "512mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      <<: *healthcheckParams

  card-db:
    build:
      context: ./card-db
      dockerfile: Dockerfile
    image: grimoire-card-db:latest
    ports:
      - "8081:8081"
    environment:
      REDIS_URL: redis://redis:6379/0
      IMAGE_CACHE_TTL: 2592000 # 30 days
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      <<: *healthcheckParams

volumes:
  redis-data:
  pgdata:
