global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: backend
  - job_name: 'query'
    metrics_path: /metrics
    static_configs:
      - targets: ['query:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: query
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
